### ISSUE TITLE
Replace webhook endpoint response

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#174]
Currently using echo. Should be replaced with a Response object.

`return new Symfony\Component\HttpFoundation\Response(1)`

**Comment by mortenson** [comment]
:wave: Hi there - we're moving all existing Mailchimp Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp/issues/3020666
