### ISSUE TITLE
'fieldable' is set twice in Mailchimp Campaign entity definition

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#175]
https://github.com/thinkshout/mailchimp/blob/8.x-1.x/modules/mailchimp_campaign/src/Entity/MailchimpCampaign.php

**Comment by mortenson** [comment]
:wave: Hi there - we're moving all existing Mailchimp Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp/issues/3020667
