### ISSUE TITLE
Illegal offset type in MailchimpSignupForm

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#179]
```
Warning: Illegal offset type in Drupal\mailchimp_signup\Form\MailchimpSignupForm->form() (line 91 of modules/mailchimp/modules/mailchimp_signup/src/Form/MailchimpSignupForm.php)
```

**Comment by mortenson** [comment]
:wave: Hi there - we're moving all existing Mailchimp Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp/issues/3020678
