### ISSUE TITLE
Sent Campaigns are not being marked with a "Sent" status

### ISSUE THREAD

**Issue by amydecat** [thinkshout/mailchimp#209]
- [x] Change status in the UI after it's sent successfully
- [x] Once sent, it should not have the ability to be edited.

**Comment by amydecat** [comment]
I cleared the cache and the 'sent' status appeared, and the campaigns became un-editable. Apparently, this cache code is not currently working - will require further investigation: 

https://github.com/thinkshout/mailchimp/blob/8.x-1.x/modules/mailchimp_campaign/mailchimp_campaign.module#L179-L180

**Comment by ruscoe** [comment]
Turns out the campaign status is still "sending" at the time we receive the response from the API. [This commit](https://github.com/thinkshout/mailchimp/commit/e551be57976b9e87b03c202ce2a75c5eee817fb3) accounts for that, but we don't have anything in place to update the status after the send action, so the status will be "sending" until the next cache clear.

We could just invalidate the cache every time a campaign is loaded if it has a "sending" status.

**Comment by amydecat** [comment]
Fixed - see above commit. 👆
