### ISSUE TITLE
Update mailchimp.make.example

### ISSUE THREAD

**Issue by jasonhildebrand** [thinkshout/mailchimp#234]
The URLs given the the example drush makefile are out of date.  I figured it out eventually, but am hoping we can update this file to help others out.

Several files I found while googling DID NOT work:
  https://github.com/thinkshout/mailchimp-api-php/archive/v1.0.6.zip
  https://github.com/thinkshout/mailchimp-api-php/files/710410/v1.0.6-package.zip

This was due to presence of a __MACOSX subdirectory in the first file (at least I think this was the cause - when drush unpacked the zip, the actual src files were one level deeper than they need to be).  And in the 
second case, the "vendor" directory was missing, which contains the required dependencies (guzzle, etc) - so was unusable.

The correct (and latest) URL for the v3 API is:
  https://github.com/thinkshout/mailchimp-api-php/releases/download/v1.0.7/v1.0.7-package.zip

If you could update that, I think it will help other users in the future.

**Comment by mortenson** [comment]
:wave: Hi there - we're moving all existing Mailchimp Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp/issues/3020683
