### ISSUE TITLE
Improve subscription UX when interest groups present

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp#235]
The goal should be to match as closely as possible the MailChimp signup form functionality. 

## MailChimp Field on new user account form
This would display only the interest groups if they exist and the user would be automatically "Subscribed" to the list if any interest group is checked.

[Newsletter Subscription Label]
- [ ] Interest Group
- [ ] Interest Group

## MailChimp Field on user account edit form
This would be similar to the account creation form, but would also include an "Unsubscribe" checkbox to unsubscribe the user if the user is subscribed to the list already. If this option was checked by the user, all interest groups would be unchecked and the user would be unsubscribed. 

[Newsletter Subscription Label]
- [ ] Interest Group
- [ ] Interest Group
 --
_You are currently subscribed to [current_list]. Manage your interest group preferences or unsubscribe from all below._ 
- [ ] Unsubscribe from all

**Comment by mortenson** [comment]
:wave: Hi there - we're moving all existing Mailchimp Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp/issues/3020684
