### ISSUE TITLE
Mailchimp rebrand changes

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp#237]
## Overview
Mailchimp changed their branding and in so doing they also changed the way the name should be typed. The name should now be used as `Mailchimp`, or title case. These changes need to happen on the https://www.drupal.org/project/mailchimp and https://www.drupal.org/project/mailchimp_ecommerce pages, as well as any README.txt files or other code the name is referenced. 

- [ ] Change all occurrences of `MailChimp` to `Mailchimp`.

**Comment by mortenson** [comment]
:wave: Hi there - we're moving all existing Mailchimp Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp/issues/3020685
