### ISSUE TITLE
Add Menu Items as an option for Page views (node-style)

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#55]
Currently, when creating a signup form with a page view, a path is required. But that path is inaccessible by both the menu system and directly until the menu cache is cleared. We do something similar when creating entity types.

As a bonus, we should make adding menu items an option when creating a signup form with a page display, similar to how Views handles it. Not sure off hand how hard that is ...

**Comment by unclegcb** [comment]
Well, given how poorly Views does it (you can only add the menu items to the top level of the menu) I suspect it might not be the simplest. Although it doesn't _sound_ too painful.

**Comment by levelos** [comment]
Actually forget Views, that's a feature for regular nodes as well. Might be worth a quick look, not a requirement for release.

**Comment by unclegcb** [comment]
Original ticket resolved. Looked into the menu piece and it's a bit complicated. A patch here for some good beginnings on it but I think this might be reaching for the beta release.
https://gist.github.com/unclegcb/179da7c6e49ebee4dd9c

**Comment by mortenson** [comment]
:wave: Hi there - we're moving all existing Mailchimp Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp/issues/3020663
