### ISSUE TITLE
error when changing email address and view activity

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#61]
> ( ! ) Fatal error: Cannot use object of type stdClass as array in /Users/lev/Sites/mailchimp_dev/profiles/mailchimp_dev/modules/mailchimp/mailchimp/ odules/mailchimp_activity/mailchimp_activity.module on line 147

Offending code:

``` php
      $newcache = array();
      if ($cache) {
        $newcache = $cache;
      }
      $newcache[$email] = $memberactivity;
```

Looks like introduced in 00c7d1f. Wondering why we're no longer caching for list-email combo?

**Comment by unclegcb** [comment]
I don't recall why it changed to a single massive cache. Seems like a bad idea. I also moved all the caching in the core module to "mailchimp_cache" cache, so I'll update this to match and to restore the granular caching. Also thinking I'll do some renaming on the cache functions to remove all the redundant "mailchimp_" since they are all going into a custom cache.
