### ISSUE TITLE
Consider adding a "managed" setting at the field level

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#76]
Currently, to have a list membership managed "automatically", you have to:
- Set the default value to subscribed
- Hide on registration form
- Change display settings to hidden

Adding this setting would eliminate those steps and simplify the instance form a bit. The only display option would be the subscription status.

/cc @unclegcb

**Comment by mortenson** [comment]
:wave: Hi there - we're moving all existing Mailchimp Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp/issues/3020665
