### ISSUE TITLE
content import and merge vars are not available when no template is selected

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#84]

**Comment by ruscoe** [comment]
Changed committed to pull request https://github.com/thinkshout/mailchimp/pull/77

entity_import_tag was actually required, so I put a slightly improved version of the field back. It's used to display the entity import code when the user clicks the "import" link but hasn't selected a text field to import into. It's a fallback to prevent the user being confused when nothing happens.

I had to spend time on the old bug that prevents merge tags being updated when the user changes the current list, due to there being no way to see merge vars when editing non-template content while that bug existed.

That bug still exists when a template is being used. It's a more complicated fix and will take time, but I don't want to delay the release. The workaround is to select the template after selecting the list.
